// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: health_enpoint.proto

package consul

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import structs "github.com/hashicorp/consul/agent/structs"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthClient interface {
	ServiceNodes(ctx context.Context, in *structs.ServiceSpecificRequest, opts ...grpc.CallOption) (*structs.IndexedCheckServiceNodes, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) ServiceNodes(ctx context.Context, in *structs.ServiceSpecificRequest, opts ...grpc.CallOption) (*structs.IndexedCheckServiceNodes, error) {
	out := new(structs.IndexedCheckServiceNodes)
	err := c.cc.Invoke(ctx, "/consul.Health/ServiceNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
type HealthServer interface {
	ServiceNodes(context.Context, *structs.ServiceSpecificRequest) (*structs.IndexedCheckServiceNodes, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_ServiceNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structs.ServiceSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ServiceNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consul.Health/ServiceNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ServiceNodes(ctx, req.(*structs.ServiceSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consul.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceNodes",
			Handler:    _Health_ServiceNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health_enpoint.proto",
}

func init() {
	proto.RegisterFile("health_enpoint.proto", fileDescriptor_health_enpoint_d7bd965be495a3bd)
}

var fileDescriptor_health_enpoint_d7bd965be495a3bd = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x31, 0xae, 0xc2, 0x30,
	0x10, 0x44, 0x7f, 0x95, 0x22, 0xfa, 0x55, 0x44, 0x95, 0x06, 0xc1, 0x01, 0x62, 0x09, 0x0a, 0x0e,
	0x40, 0x03, 0x0d, 0x05, 0xa1, 0x06, 0x25, 0xeb, 0x21, 0xb6, 0x08, 0x5e, 0x63, 0xaf, 0x11, 0xc7,
	0x47, 0x4a, 0x08, 0xa2, 0x1a, 0x69, 0xe6, 0xe9, 0x4d, 0x3e, 0x33, 0x68, 0x7a, 0x31, 0x17, 0x38,
	0xcf, 0xd6, 0x49, 0xe5, 0x03, 0x0b, 0x17, 0x19, 0xb1, 0x8b, 0xa9, 0x2f, 0x37, 0x9d, 0x15, 0x93,
	0xda, 0x8a, 0xf8, 0xae, 0x4c, 0x13, 0x8d, 0x25, 0x0e, 0x5e, 0x8d, 0xa3, 0x6a, 0x3a, 0x38, 0x51,
	0x51, 0x42, 0x22, 0x89, 0x53, 0x8e, 0x82, 0xd5, 0x39, 0xcf, 0x76, 0x83, 0xb8, 0x38, 0xe5, 0xff,
	0x35, 0xc2, 0xd3, 0x12, 0x0e, 0xac, 0x11, 0x8b, 0x79, 0x35, 0x91, 0x9f, 0xba, 0xf6, 0x20, 0x7b,
	0xb5, 0x74, 0xc4, 0x23, 0x21, 0x4a, 0xb9, 0xf8, 0x02, 0x7b, 0xa7, 0xf1, 0x82, 0xde, 0x1a, 0xd0,
	0xed, 0xd7, 0xb1, 0xfc, 0x6b, 0xb3, 0xe1, 0x66, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xc9,
	0x67, 0x7a, 0xbf, 0x00, 0x00, 0x00,
}
